# Generated by Django 5.2 on 2025-05-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinvetory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinvetory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
